server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/open-alert
    username: local
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/